services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data

  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

  test:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate db:seed && bundle exec rspec"
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_test
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: test

volumes:
  postgres13:
  redis_data:

